---

- hosts: test
  remote_user: deploy
  become: "yes"
  become_user: root
  become_method: sudo

  vars:
     common_name_clients:
       - myvpn
     vpn_serv_or_ip: 89.208.208.140

  roles:
    - { role: common, tags: ['common'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: openvpn, tags: ['openvpn'] }
