---

- hosts: test
  remote_user: deploy
  become: "yes"
  become_user: root
  become_method: sudo

  vars:
     common_name_clients:
       - cert101
       - cert102
       - cert103
       - cert104
       - cert105
       - cert106
       - cert107
       - cert108
       - cert109
       - cert110
       - cert111
       - cert112
       - cert113

  roles:
    - { role: common, tags: ['common'] }
    - { role: ufw, tags: ['ufw'] }
#   - bind9
    - { role: openvpn, tags: ['openvpn'] }
