---

- hosts: aws
  remote_user: deploy
  become: "yes"
  become_user: root
  become_method: sudo

  vars:
     common_name_clients:
       - myvpn
       - vpn_cert2
       - vpn_cert3
     vpn_serv_or_ip: ec2-18-184-213-47.eu-central-1.compute.amazonaws.com

  roles:
    - { role: common, tags: ['common'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: openvpn, tags: ['openvpn'] }
    - { role: dns, tags: ['dns'] }
