---
your_user: user
link_to_easy_rsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-unix-v3.0.6.tgz"
easyrsa_ver: "EasyRSA-v3.0.6"
path_to_easy_rsa: "/home/{{ your_user }}"
EASYRSA_REQ_COUNTRY: "US"
EASYRSA_REQ_PROVINCE: "California"
EASYRSA_REQ_CITY: "San Francisco"
EASYRSA_REQ_ORG: "Copyleft Certificate Co"
EASYRSA_REQ_EMAIL: "me@example.net"
EASYRSA_REQ_OU: "My Organizational Unit"
CA_pass: "ier4ohbo6si2aidai7ahzuangaishoquohdahjohseixu1pi2meegh0gae8ePohr4ein9jeeMoo5pheeyeegahph9phaisaiX1yo"
common_name: server
common_name_clients: client
